import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased dark bg-background text-foreground`}
      >
        <div className="grainy-bg-overlay pointer-events-none fixed inset-0 z-0" aria-hidden="true"></div>
        <div className="relative min-h-screen w-full overflow-x-hidden z-10">
          <nav className="w-full flex items-center justify-between py-4 px-8 border-b border-border bg-background/80 backdrop-blur sticky top-0 z-50">
            <div className="text-xl font-bold tracking-tight">
              Resu<span className="text-primary">mind</span>
            </div>
            <div></div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
